### ISSUE TITLE
Why only hard type => chartist-chart-type="Bar"

### ISSUE THREAD

**Issue by shlomogoldstein** [paradox41/angular-chartist.js#60]
Using 

```
// ctrl 
$scope.barType = "Bar";

// html
... chartist-chart-type="barType" ...
```

fails with

```
TypeError: e[this.chartType] is not a function
    at t.a.value (http://localhost:6040/bower_components/angular-chartist.js/dist/angular-chartist.min.js:1:1460)
    at new t (http://localhost:6040/bower_components/angular-chartist.js/dist/angular-chartist.min.js:1:1055)
    at Object.invoke (http://localhost:6040/bower_components/angular/angular.js:4452:17)
    at ident.$get.extend.instance (http://localhost:6040/bower_components/angular/angular.js:9001:34)
    at nodeLinkFn (http://localhost:6040/bower_components/angular/angular.js:8111:36)
    at compositeLinkFn (http://localhost:6040/bower_components/angular/angular.js:7543:13)
    at compositeLinkFn (http://localhost:6040/bower_components/angular/angular.js:7547:13)
    at compositeLinkFn (http://localhost:6040/bower_components/angular/angular.js:7547:13)
    at compositeLinkFn (http://localhost:6040/bower_components/angular/angular.js:7547:13)
    at publicLinkFn (http://localhost:6040/bower_components/angular/angular.js:7418:30) <div ui-view="" class="ng-scope">
```

**Comment by paradox41** [comment]
You need to evaluate `barType`

```html
chartist-chart-type="{{barType}}"
```

Since the directive [only accepts strings](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L71)
